### ISSUE TITLE
Persist link app installation

### ISSUE THREAD

**Issue by blazo121** [jauntybrain/flow-links-extension#2]
Hi

I setup flow links and link doesn't persist app installation.

**Comment by jauntybrain** [comment]
Hi! Could you please tell me more about the problem? I'll be glad to help you solve it!

**Comment by blazo121** [comment]
I'm trying to replace firebase dynamic link with flow links. 

Flow links works:
- when app is installed open app
- when app is not installed open store

but not working:
- when app is not installed it open store after installation of app, open app, app not receive link 

I'm refering to flow when app is not installed https://mobikul.com/wp-content/uploads/2022/08/firebase_dynamic_link.png

**Comment by jauntybrain** [comment]
I see -- you are referring to deferred links. Unfortunately, due to platform restrictions from Apple, deferred links have become nearly impossible to implement without collecting sensitive user information. These and other limitations are one of the main reasons for Firebase shutting down Dynamic Links. 

With that said, FlowLinks, unfortunately, currently don't support deferred links. However, I am exploring different options and will be sure to make an update if I come up with a good implementation!

**Comment by blazo121** [comment]
Thank you for your response. Do you have any estimate of when this feature might be available?

**Comment by YoungrakSon** [comment]
> I see -- you are referring to deferred links. Unfortunately, due to platform restrictions from Apple, deferred links have become nearly impossible to implement without collecting sensitive user information. These and other limitations are one of the main reasons for Firebase shutting down Dynamic Links.
> 
> With that said, FlowLinks, unfortunately, currently don't support deferred links. However, I am exploring different options and will be sure to make an update if I come up with a good implementation!

Bro Thank you for your contribution I love it 
I think I can go with everything simple without deferred deep link. apple sucks though

**Comment by jauntybrain** [comment]
> Thank you for your response. Do you have any estimate of when this feature might be available?

Cannot say for sure for iOS, as it fully depends on Apple. 

For Android, a [Google Play Install Referrer API](https://developer.android.com/google/play/installreferrer) exists, which might help you send data from GooglePlay to the newly installed application.
