### ISSUE TITLE
Don't redirect

### ISSUE THREAD

**Issue by GerardoBase** [jauntybrain/flow-links-extension#3]
I installed [the extension](https://extensions.dev/extensions/jauntybrain/firebase-flow-links) and tried to set up a new link, but the website doesn't redirect to any store. I created the link manually in the Firestore database and another one with [the dashboard](https://edit.flowlinks.app/home) (It doesn't work in both cases).

I detected the script on the website is: 
`if ("false" == "true") {`
`     var result = detect.parse(navigator.userAgent);`
`     if (result.os.family === "iOS") {`
`        ...`
Even when I set up `redirectToStore` `true`.

Also, the `appStoreID` is not concat properly on the URL to redirect. It just renders:
`window.location.href = "https://apps.apple.com/us/app/";`

**Comment by jauntybrain** [comment]
Hi @GerardoBase, thanks for reporting this issue! 
I will make sure to check it out and push a fix as soon as possible. Will keep you posted.

**Comment by jauntybrain** [comment]
Hi @GerardoBase! I've been running a lot of tests on this case today and came to an interesting conclusion - Firestore data seems to be getting cached based on the Cloud Function instance.

A simple example: 

1. Install the extension, open the `/welcome` link in the browser - it should recognize the link and show the "Redirecting..." text. 
2. Right after that, try changing the `path` value in Firestore from `/welcome` to something else, e.g. `/test`.
3. Now `/welcome` should return 404 and `/test` should return "Redirecting...". However, this never happens - the `/welcome` link keeps working, but the weirdest part is that `/test` will also work, meaning that Firestore query worked on a new request but somehow uses cached data for the old one.
4. Now try accessing `/welcome` from a different device (a phone, for example) - it should return 404.

This is a very interesting case as I could not find any similar issues on the Web, and even playing around with max/min instances did not resolve it. I'll make sure to keep investigating in order to resolve this ASAP!

P.S. the `appStoreID` is breaking also due to `redirectToStore` not being updated correctly, so fixing the latter will fix the former.

**Comment by jauntybrain** [comment]
@GerardoBase, I just released a new version (0.1.4) that should resolve this issue.
